service: cvs-svc-authoriser

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

provider:
  region: eu-west-1
  name: aws
  runtime: nodejs22.x
  timeout: 60
  httpApi:
    authorizers:
      authoriserFunction:
        type: request
        functionName: authoriserFunction
        payloadVersion: "2.0"
        enableSimpleResponses: false
        identitySource:
          - $request.header.Authorization

functions:
  authoriserFunction:
    handler: src/handler.handler
  testFunction:
    handler: tests/handler.test
    events:
      - httpApi:
          path: /testFunction
          method: POST
          authorizer:
            name: authoriserFunction
